// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDziLgcU0u4-EGiNnucae12vM855ge-ZP4',
    appId: '1:950606991263:web:1e2527f8a74e0157f437aa',
    messagingSenderId: '950606991263',
    projectId: 'registrationform-99493',
    authDomain: 'registrationform-99493.firebaseapp.com',
    storageBucket: 'registrationform-99493.firebasestorage.app',
    measurementId: 'G-HKRPXDWVTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UOR0Lv8KX6ej-GR3ui8a1Gtz6cbLoW4',
    appId: '1:950606991263:android:1abcd0c5b1c57512f437aa',
    messagingSenderId: '950606991263',
    projectId: 'registrationform-99493',
    storageBucket: 'registrationform-99493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTaqzAvPuYLnC2cwqV2lUyMmkMDITA7f4',
    appId: '1:950606991263:ios:0c8f10e402260ae2f437aa',
    messagingSenderId: '950606991263',
    projectId: 'registrationform-99493',
    storageBucket: 'registrationform-99493.firebasestorage.app',
    iosBundleId: 'com.example.registrationform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTaqzAvPuYLnC2cwqV2lUyMmkMDITA7f4',
    appId: '1:950606991263:ios:0c8f10e402260ae2f437aa',
    messagingSenderId: '950606991263',
    projectId: 'registrationform-99493',
    storageBucket: 'registrationform-99493.firebasestorage.app',
    iosBundleId: 'com.example.registrationform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDziLgcU0u4-EGiNnucae12vM855ge-ZP4',
    appId: '1:950606991263:web:f684b3edee7d5267f437aa',
    messagingSenderId: '950606991263',
    projectId: 'registrationform-99493',
    authDomain: 'registrationform-99493.firebaseapp.com',
    storageBucket: 'registrationform-99493.firebasestorage.app',
    measurementId: 'G-SY23EHEBGL',
  );
}
